# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name=b'email address')),
                ('call_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bv_id', models.IntegerField(unique=True)),
                ('date_of_birth', models.DateField()),
                ('cell', models.CharField(max_length=100)),
                ('add_email', models.EmailField(max_length=50)),
                ('platoon', models.CharField(max_length=20)),
                ('squadron', models.CharField(max_length=20)),
                ('squad', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
